In [1]:
import pandas as pd

In [2]:
df_sj, df_rr = pd.read_csv('../datasets/superjob_vacancies.csv'), pd.read_csv('../datasets/rabota_ru_formated.csv')
df_sj

,id,Название вакансии,Минимальная зарплата,Максимальная зарплата,Валюта,Категория,Детальные категории,Город,Метро,Линия метро,...,Индуcтрия,Кол-во персонала в компании,Кол-во размещенных вакансий,Название компании,Опыт,График работы,Образование,Широта,Долгота,ссылка
0,31948884,Системный администратор,65000,0,rub,"['IT, Интернет, связь, телеком']","['Системное администрирование', 'Техническая п...",Санкт-Петербург,"['Петроградская', 'Чёрная Речка']","['Московско-Петроградская', 'Московско-Петрогр...",...,NaN,50 — 100,8.0,Санкт-Петербургский морской рыбопромышленный к...,От 1 года,Полный рабочий день,Не имеет значения,59.980118,30.279800,https://spb.superjob.ru/vakansii/sistemnyj-adm...
1,50742146,Администратор магазина,94900,113900,rub,"['Промышленность, производство', 'IT, Интернет...","['Промышленное оборудование', 'Внедрение и соп...",Санкт-Петербург,[],[],...,NaN,более 5000,49868.0,Пятёрочка,От 1 года,Полный рабочий день,Не имеет значения,59.903267,30.465429,https://spb.superjob.ru/vakansii/administrator...
2,46781727,Системный администратор,45000,0,rub,"['IT, Интернет, связь, телеком']","['Сетевые технологии', 'Системное администриро...",Санкт-Петербург,"['Невский Проспект', 'Гостиный Двор', 'Василео...","['Московско-Петроградская', 'Невско-Василеостр...",...,NaN,менее 50,2.0,Государственная библиотека,От 6 лет,Полный рабочий день,Высшее,59.938953,30.315643,https://spb.superjob.ru/vakansii/sistemnyj-adm...
3,51673017,Инженер по АСУ ТП (ТЭЦ-21),95526,95526,rub,"['IT, Интернет, связь, телеком', 'Промышленнос...","['Инжиниринг', 'Промышленное оборудование']",Санкт-Петербург,"['Гражданский Проспект', 'Девяткино', 'Проспек...","['Кировско-Выборгская', 'Кировско-Выборгская',...",...,NaN,более 5000,60.0,Территориальная генерирующая компания №1,От 1 года,Полный рабочий день,Не имеет значения,60.057323,30.476370,https://spb.superjob.ru/vakansii/inzhener-po-a...
4,51729020,Инженер 1 категории (отдел по работе с обращен...,75000,0,rub,"['Административная работа, секретариат, АХО', ...","['Делопроизводство', 'Диспетчерская служба', '...",Санкт-Петербург,[],[],...,NaN,500 — 1000,0.0,Жилищное агентство Красногвардейского района С...,От 1 года,Полный рабочий день,Среднее специальное,59.949829,30.412159,https://spb.superjob.ru/vakansii/inzhener-1-ka...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2674,46603831,Рабочий по комплексному обслуживанию здания,90000,0,rub,"['Строительство, проектирование, недвижимость']","['Строительно-монтажные работы', 'Эксплуатация...",Щелково,[],[],...,NaN,100 — 500,6.0,Техноколор,От 1 года,Полный рабочий день,Среднее специальное,NaN,NaN,https://schelkovo.superjob.ru/vakansii/rabochi...
2675,47869139,Мастер по текущему ремонту (Плотник),65000,65000,rub,"['Рабочий персонал', 'Строительство, проектиро...","['Рабочий персонал, разное', 'Квалифицированны...",Санкт-Петербург,"['Петроградская', 'Чёрная Речка', 'Чкаловская'...","['Московско-Петроградская', 'Московско-Петрогр...",...,NaN,500 — 1000,0.0,Управление комфортом,От 1 года,Полный рабочий день,Не имеет значения,59.958511,30.289700,https://spb.superjob.ru/vakansii/master-po-tek...
2676,51707520,Электромонтер контактной сети,51000,72000,rub,"['Строительство, проектирование, недвижимость'...","['Электроснабжение', 'Квалифицированный рабочий']",Батайск,[],[],...,NaN,более 5000,6387.0,Российские железные дороги,Без опыта,Полный рабочий день,Не имеет значения,47.154537,39.753277,https://bataisk.superjob.ru/vakansii/elektromo...
2677,51760926,Стажер системный инженер (BigData),0,0,rub,"['IT, Интернет, связь, телеком', 'Строительств...","['Инжиниринг', 'Сетевые технологии', 'Начало к...",Москва,[],[],...,NaN,менее 50,15.0,КРОК,Без опыта,Полный рабочий день,Не имеет значения,NaN,NaN,https://www.superjob.ru/vakansii/stazher-siste...
2678,51863366,Автокурьер на личном авто (Оплата патента),70000,160000,rub,"['Строительство, проектирование, недвижимость'...","['Конструирование', 'Услуги, ремонт, сервисное...",Москва,['Парк Победы'],['Калининско-Солнцевская'],...,NaN,NaN,NaN,NaN,Без опыта,Полный рабочий день,Не имеет значения,55.735630,37.524506,https://www.superjob.ru/vakansii/avtokurer-na-...

In [5]:
df_rr

,Unnamed: 0,Название вакансии,Зарплата,Требуемые навыки,Теги,Компания,Метро,Адрес,Город,Сфера,Общее название профессии,Опыт работы,Образование,Ссылка,Минимальная зарплата,Максимальная зарплата
0,0,Парикмахер-универсал,60000— 200000 руб.,"['диплом об окончании курсов парикмахеров', 'Р...","['Вакансия недели', 'Быстрый отклик']",Шевченко Татьяна Анатольевна,"['Петровский парк,', 'Петровский парк']","Петровский парк, Петровский парк,г Москва, ул ...",Москва,Работа в сфере красоты,Парикмахер,от 3 лет,любое,https://www.rabota.ru/vacancy/54255960/?search...,60000.0,200000.0
1,1,Ведущий научный сотрудник,от 150000 руб.,"['MS Office', 'MS Office Excel', 'MS Office W...",Без тега,ФГБУ «ЦНИИОИЗ» МИНЗДРАВА РОССИИ,['Бутырская'],"Бутырская,г Москва, ул Добролюбова, д 11",Москва,Работа в сфере образования,Научный сотрудник,от 1 года,высшее,https://www.rabota.ru/vacancy/54244351/?search...,150000.0,NaN
2,2,Водитель-курьер на доставку сантехники,по договоренности,"['пунктуальность', 'безаварийное вождение', 'д...",Без тега,Яндекс.Доставка,NaN,г Москва,Москва,NaN,NaN,без опыта,любое,https://www.rabota.ru/vacancy/54238467/?search...,NaN,NaN
3,3,Водитель-курьер на личном авто,по договоренности,"['пунктуальность', 'безаварийное вождение', 'д...",Без тега,Яндекс.Доставка,NaN,г Москва,Москва,NaN,NaN,без опыта,любое,https://www.rabota.ru/vacancy/54238448/?search...,NaN,NaN
4,4,Медицинский писатель (Координационный центр фе...,по договоренности,"['коммуникабельность', 'ведение переговоров', ...",Без тега,ФГБУ «ЦНИИОИЗ» МИНЗДРАВА РОССИИ,['Гражданская'],"Гражданская,г Москва, ул Вучетича, д 12",Москва,Работа в сфере культуры,Писатель,от 1 года,высшее,https://www.rabota.ru/vacancy/54223769/?search...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12641,12676,Водитель категории С (вахта),180000— 260000 руб.,"['ответственность', 'устройство автомобилей', ...",Без тега,Кашалот,['Площадь Революции'],"Площадь Революции,г Москва",Московская область,Работа на транспорте,Водитель,от 1 года,любое,https://msk-region.rabota.ru/vacancy/54241400/...,180000.0,260000.0
12642,12677,Разнорабочий,120000— 180000 руб.,нет,Без тега,"ООО ""РЕГИОНСТРОЙ""",['Площадь Революции'],"Площадь Революции,г Москва",Московская область,Разнорабочий,NaN,без опыта,любое,https://msk-region.rabota.ru/vacancy/53731894/...,120000.0,180000.0
12643,12678,Водитель,170000— 180000 руб.,"['ответственность', 'пунктуальность', 'безавар...",['Пенсионерам'],ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ МАНЕНКОВА ЛИЛИЯ...,['Площадь Революции'],"Площадь Революции,г Москва",Московская область,Работа на транспорте,Водитель,от 1 года,любое,https://msk-region.rabota.ru/vacancy/52095858/...,170000.0,180000.0
12644,12679,Рекрутер,10000— 250000 руб.,нет,Без тега,САМОХВАЛОВ ВИКТОР ВЛАДИМИРОВИЧ,['Площадь Революции'],"Площадь Революции,г Москва",Московская область,Работа в сфере HR,Менеджер по персоналу,без опыта,любое,https://msk-region.rabota.ru/vacancy/50488347/...,10000.0,250000.0
12645,12680,Охранник,по договоренности,нет,Без тега,"ООО ЧОО ""ГРОЗА СБ""",['Сокольники'],"Сокольники,г Москва",Московская область,Работа в сфере безопасности,NaN,без опыта,любое,https://msk-region.rabota.ru/vacancy/50487793/...,NaN,NaN